#!/usr/bin/env bash
# provision-accounts.sh — Create fresh test accounts for a farm run.
#
# Fetches the test API key from GCP Secret Manager, generates a unique run ID,
# registers User A and User B against the test API, and writes credentials to
# scripts/test-farm/.farm-env (gitignored).
#
# Usage:
#   scripts/test-farm/provision-accounts.sh
#
# Prerequisites:
#   - gcloud CLI installed and authenticated (gcloud auth application-default login)
#   - jq installed
#   - curl installed
#
# Outputs:
#   scripts/test-farm/.farm-env  — sourced by Maestro run scripts
#   Stdout summary of accounts created

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FARM_ENV="${SCRIPT_DIR}/.farm-env"
TEST_API="https://test.api.heirlooms.digital"
GCP_PROJECT="heirlooms-495416"
SECRET_NAME="heirlooms-test-api-key"

echo "=== Heirlooms device farm — account provisioning ==="

# --- 1. Fetch test API key from Secret Manager ---
echo "[provision] Fetching test API key from Secret Manager ..."
API_KEY=$(gcloud secrets versions access latest \
  --secret="${SECRET_NAME}" \
  --project="${GCP_PROJECT}" \
  --quiet)

if [[ -z "${API_KEY}" ]]; then
  echo "ERROR: Could not retrieve secret ${SECRET_NAME} from ${GCP_PROJECT}." >&2
  exit 1
fi

# --- 2. Generate unique run ID ---
RUN_ID=$(date +%s)
USER_A_USERNAME="farm-a-${RUN_ID}"
USER_B_USERNAME="farm-b-${RUN_ID}"

# Random 24-character passwords (alphanumeric)
USER_A_PASSWORD=$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24)
USER_B_PASSWORD=$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24)

echo "[provision] Run ID: ${RUN_ID}"
echo "[provision] User A: ${USER_A_USERNAME}"
echo "[provision] User B: ${USER_B_USERNAME}"

# --- 3. Create invite token for User A ---
echo "[provision] Creating invite token for User A ..."
TOKEN_A=$(curl -sf -X POST \
  -H "X-API-Key: ${API_KEY}" \
  "${TEST_API}/api/auth/invites" \
  | jq -r '.token')

if [[ -z "${TOKEN_A}" || "${TOKEN_A}" == "null" ]]; then
  echo "ERROR: Failed to create invite token for User A." >&2
  exit 1
fi

# --- 4. Register User A ---
echo "[provision] Registering ${USER_A_USERNAME} ..."
curl -sf -X POST \
  -H "Content-Type: application/json" \
  -d "{\"username\":\"${USER_A_USERNAME}\",\"password\":\"${USER_A_PASSWORD}\",\"token\":\"${TOKEN_A}\"}" \
  "${TEST_API}/api/auth/register" \
  > /dev/null

# --- 5. Create invite token for User B ---
echo "[provision] Creating invite token for User B ..."
TOKEN_B=$(curl -sf -X POST \
  -H "X-API-Key: ${API_KEY}" \
  "${TEST_API}/api/auth/invites" \
  | jq -r '.token')

if [[ -z "${TOKEN_B}" || "${TOKEN_B}" == "null" ]]; then
  echo "ERROR: Failed to create invite token for User B." >&2
  exit 1
fi

# --- 6. Register User B ---
echo "[provision] Registering ${USER_B_USERNAME} ..."
curl -sf -X POST \
  -H "Content-Type: application/json" \
  -d "{\"username\":\"${USER_B_USERNAME}\",\"password\":\"${USER_B_PASSWORD}\",\"token\":\"${TOKEN_B}\"}" \
  "${TEST_API}/api/auth/register" \
  > /dev/null

# --- 7. Write .farm-env ---
cat > "${FARM_ENV}" <<EOF
# Auto-generated by provision-accounts.sh — do not commit.
# Sourced by Maestro run scripts.
RUN_ID=${RUN_ID}
USER_A_USERNAME=${USER_A_USERNAME}
USER_A_PASSWORD=${USER_A_PASSWORD}
USER_B_USERNAME=${USER_B_USERNAME}
USER_B_PASSWORD=${USER_B_PASSWORD}
EOF

chmod 600 "${FARM_ENV}"

echo ""
echo "=== Provisioning complete ==="
echo "  Credentials written to ${FARM_ENV}"
echo "  User A: ${USER_A_USERNAME}"
echo "  User B: ${USER_B_USERNAME}"
echo "  Source .farm-env before running Maestro flows."
